### ISSUE TITLE
Compilation procedure

### ISSUE THREAD

**Issue by brucellino** [KRHenninger/FMD-codes-from-T.-Neff-#1]
Hi @KRHenninger, thanks for creating the repo and putting in the code - and sorry for taking a while to get back to you.

I am having trouble compiling this code and I would like to get some input from you.  

Having untarred the code, I see that the Makefile uses includes, and there are a few templates for various ubuntu distributions. I copied the latest one (wheezy) to `Makefile.inc`.

I went into `src` and naively tried `make`, which immediately gave me an error : 

```
make: *** No rule to make target 'fmd/Constraintj2.h', needed by 'minenergyconorthogonalproj.d'.  Stop.
```

This _seems_ to be a simple naming problem, since `fmd/ConstraintJ2.h` does exist - however `fmd/ConstraintJ2.h` _also_ exists.

**Question** : Can you tell me if these are supposed to be separate files ? If so, the tarball seems to be missing some files.

Thanks

**Comment by KRHenninger** [comment]
Hi Bruce! 
Thanks so much for all the work you've put in on my behalf! I am glad to hear you had the same issues with the make - that's exactly what I ran into! 

Unfortunately, if there are missing files then I don't have them. That's all I inherited, so to speak. I always used the "ready-made" executables that are in there, but I understand from you and Sean that rebuilding them is better.  

To answer your question: No, I think they are meant to be the same file. If so, at least we've got what we need, as far as I can gather.

Let me know if that is any help at all!
Thanks!

**Comment by brucellino** [comment]
Hi @KRHenninger 

> that's exactly what I ran into! 

Always good to know I'm not going crazy ! 

As for the re-building - yes, we have to do that, because in principle in a distributed system like the grid, you have several target architectures and operating systems. CODE-RADE does the compilation for all of the supported targets, so we need to work with the source code. If we use plain binaries, we cannot guarantee that the application will execute correctly on the sites. There is also the matter of transparency between the user and the site administrator - if you send untested and unverified binaries to the sites, this will cause suspicion. 

This code looks like it was built with a Windows-based compiler - can you confirm that ? I say this because in some Windows applications there is case-insensitivity and I see that some windows-specific headers are being included.

**Comment by brucellino** [comment]
Ok, I've solved this issue, but before I close it, let me describe what I did.

# Constraint[J,j]2.

There was a simple naming problem with ConstraintJ2. My concern was that there were _supposed_ to be two different classes : `ConstraintJ2` and `Constraintj2` which actually did different things. However, when I did create separate headers, class and dependency files for this, the linker failed saying that some things were already declared. This said to me that they were actually the same thing. So, `Constraintj2.*` is not needed. 

I fixed this by replacing `Constraintj2` with `ConstraintJ2` in the repo, and the compilation passed that stage.

# Hard-coded headers

There are some places (Makefiles, dependency files) where the location of the dependency headers and libraries are hardcoded. Since we are working in an environment where we have no explicit control over where these will be, we need to refer to them by their variable location. These variables - such as 
- `${LAPACK_DIR}`
- `${OPENMPI_DIR}` 
- `${GCC_DIR}` 

etc are provided by the modulefiles that CODE-RADE delivers. 

The modulefiles that are needed to compile this code are  : 

```
module list
Currently Loaded Modulefiles:
  1) ncurses/5.9               3) mpfr/3.1.2                5) gcc/5.2.0                 7) openmpi/1.8.8-gcc-5.2.0
  2) gmp/6.1.0                 4) mpc/1.0.1                 6) torque/2.5.13-gcc-5.2.0   8) lapack/3.6.0-gcc-5.2.0
```

Using the relevant paths as variables, the code now compiles. 

# Repo cleanup.

So, to get this going, we need to clean up the repo a little. This means removing the tarball and committing the individual code files - and don't forget  the license file we discussed [on the forum](http://discourse.sci-gaia.eu/t/license-for-fmd-application/2157/3)
