### ISSUE TITLE
minimal viable test case

### ISSUE THREAD

**Issue by brucellino** [KRHenninger/FMD-codes-from-T.-Neff-#3]
Hi @KRHenninger ,
Following on from http://discourse.sci-gaia.eu/t/connecting-to-the-sa-grid-facilities-as-a-researcher/2147/2?u=brucellino 

Could you provide me with a "minimal viable test case" for the binaries that are created ? 

IE, I need to know what parameters and input file to feed the applications to test their functionality. This needs to be 
- minimal : only do basic tests.
- atomic : test one thing at a time.

Thanks !

**Comment by KRHenninger** [comment]
Hi @brucellino!

Sorry to only get back to you on this now...I forgot you didn't have any input files! The files you'll need to test something (let's say the "minenergy" program, or any of the "min..." stuff, which is basically all I use) are a ".fmd" file (I'll upload one for Helium 4 - nice and quick!), and a ".int" file (I'll upload the one I currently use "AV18-UsrgD2000f-v11ls-2.0.int"). 

As long as we can run something like "minenergy AV18-UsrgD2000f-v11ls-2.0.int He4.fmd", we know it's working!

Let me know if that is vaguely useful, or if you need something else! 
Thanks!!

**Comment by brucellino** [comment]
> "minenergy AV18-UsrgD2000f-v11ls-2.0.int He4.fmd"
> thanks, that's perfect. 

If you could accept the Pull Requests #2, then add your int file to the repo, I can take it from there.

**Comment by KRHenninger** [comment]
Hi Bruce! That's great! I hope I did the right thing...now you should have AV18-UsrgD2000f-v11ls-2.0.int! I thought I'd uploaded it earlier, but clearly didn't...my bad.
